#NAME: Shreya Raman
#EMAIL: shreyaraman99@gmail.com
#ID: 004923456

default:
	cp lab3b.py lab3b
	chmod +x lab3b

dist:
	tar -czf lab3b-004923456.tar.gz lab3b.py Makefile README

clean:
	rm -f *.err lab3b *.tar.gz
