#Name: Shreya Raman
#Email: shreyaraman99@gmail.com
#ID: 004923456

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c

dist:
	tar -czvf lab3a-004923456.tar.gz lab3a.c ext2_fs.h Makefile README

clean:
	rm -f lab3a lab3a-004923456.tar.gz 
