#NAME: Shreya Raman
#EMAIL: shreyaraman99@gmail.com
#ID: 004923456

clean:
	rm -f lab4a-004923456.tar.gz

dist:
	tar -cvzf lab4a-004923456.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

